export default tabs = {
  categories: [
    { id: 'herbs', title: 'Aromatic Herbs and Spices' },
    { id: 'cereals', title: 'Cereals and Grains' },
    { id: 'diary', title: 'Dairy and Non-Dairy' },
    { id: 'drinks', title: 'Drinks'},
    { id: 'farmInputs', title: 'Farm Inputs' },
    { id: 'fish', title: 'Fish and Sea Food' },
    { id: 'fruits', title: 'Fruits'},
    { id: 'legumes', title: 'Legumes/Pulses' },
    { id: 'liveStocks', title: 'Live Stocks' },
    { id: 'meats', title: 'Meats' },
    { id: 'nutritionalFoodSupplements', title: 'Nutritional Food Supplements'},
    { id: 'nutsKernels', title: 'Nuts and Kernels' },
    { id: 'oils', title: 'Oils' },
    { id: 'ornamental', title: 'Ornamentals'},
    { id: 'other', title: 'Others' },
    { id: 'otherServices', title: 'Other Services' },
    { id: 'pets', title: 'Pets' },
    { id: 'poultry', title: 'Poultry'},
    { id: 'processedFoodSnacks', title: 'Processed Food and Snacks' },
    { id: 'rawMaterials', title: 'Raw Materials' },
    { id: 'rootsTubers', title: 'Roots and Tubers'},
    { id: 'seeds', title: 'Seeds' },
    { id: 'soupThickner', title: 'Soup Thickner' },
    { id: 'sweetners', title: 'Sweetners' },
    { id: 'teas', title: 'Teas'},
    { id: 'toolsMachines', title: 'Tools and Machines' },
    { id: 'vegetables', title: 'Vegetables' },
  ],
  fashion: [
    { id: 'shoes', title: 'Shoes', },
    { id: 'beauty', title: 'Beauty', },
    { id: 'fashion', title: 'Fashion', },
    { id: 'places', title: 'Places', }
  ],
}
